name: Autotest using inso

on:
  push:
    branches: [ main ]

jobs:
  autotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kong/setup-inso@v1
      with:
        inso-version: 2.8.0
    - run: inso lint spec "Ply Movies API"
    - run: inso run test "Ply Movies API" --testNamePattern "Get Movie by Title" --env "ply-ct.org"