name: test

on:
  push:
    branches: [ main ]

jobs:
  autotest:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 'true'
    steps:
    - uses: actions/checkout@v2
    - uses: kong/setup-inso@v1
      with:
        inso-version: 2.4.0
    - run: inso generate config "Ply Movies API" > kong-services.yaml
    - run: inso lint spec "Ply Movies API"
    - run: inso run test "Ply Movies API" --env "OpenAPI env"
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: node --version
    - run: npm install
    - uses: ply-ct/ply-action@v1.0.4
      with:
        plyees: 'ply/**/*.flow'
